version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ginco_postgres
    restart: always
    ports:
      - "5040:5432"
    environment:
      POSTGRES_USER: ginco_user
      POSTGRES_PASSWORD: ginco_pass
      POSTGRES_DB: ginco_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ginco_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ginco.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
